import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTiktok, faTwitter } from "@fortawesome/free-brands-svg-icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="topNav">
          <div className="mainNav container">
            <div className="navItem logoContainer">
              <Image className="avatarImg" src="/images/avatar-img.png" height="100" width="100" alt="avatar image"></Image>
            </div>
            <div className="navItem navLinkContainer">
              <Link className="navLink" href="/">
                Home
              </Link>
              <Link className="navLink" href="/showcase">
                Showcase
              </Link>
              <Link className="navLink" href="/decks">
                Decks
              </Link>
            </div>
          </div>
        </nav>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">{children}</main>
        <footer className="footerWrapper">
          <div className="footerItem">
            <Link href="/">
              <FontAwesomeIcon className="socialIcon" icon={faTwitter} />
            </Link>
            <Link href="/">
              <FontAwesomeIcon className="socialIcon" icon={faTiktok} />
            </Link>
          </div>
          <div className="footerItem"></div>
        </footer>
      </body>
    </html>
  );
}
